id: 1014cfd6acd847e2a875ba9165f3d017
title: Toh_563-Upholding_the_Great_Secret_Mantra-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-26T04:14:37.687Z'
  creationid: celso
  eft-text-id: UT22084-090-007
  eft-text-version: 1.4.1 2020
  xmlns-eft: http://read.84000.co/ns/1.0
